name: toko_sandal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Firebase
  # Tips: Gunakan firebase_ui_auth jika ingin widget login instan, 
  # tapi untuk custom UI, package di bawah sudah benar.
  firebase_core: ^3.10.1    # Versi disesuaikan agar stabil dengan auth
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2

  # HTTP Client
  dio: ^5.7.0

  # Local Storage (simpan token/session)
  flutter_secure_storage: ^9.2.2

  # Utilities
  equatable: ^2.0.7
  email_validator: ^3.0.0
  flutter_svg: ^2.0.10
  intl: ^0.19.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints untuk menjaga kualitas kode
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Setup folder assets
  assets:
    - assets/icons/
    - assets/images/
