// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrBBhxLH7trX0NHKe_x16B-033Y2rL2NY',
    appId: '1:1012231416866:web:cda0267b92f8f2d462ae7b',
    messagingSenderId: '1012231416866',
    projectId: 'tokosandal-e5185',
    authDomain: 'tokosandal-e5185.firebaseapp.com',
    storageBucket: 'tokosandal-e5185.firebasestorage.app',
    measurementId: 'G-L8HT7YY4LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhM3Q2hjRdzgRwtEnUOAflQpofbhrxuxk',
    appId: '1:1012231416866:android:bb8551a0dc051b6262ae7b',
    messagingSenderId: '1012231416866',
    projectId: 'tokosandal-e5185',
    storageBucket: 'tokosandal-e5185.firebasestorage.app',
  );
}
